### ISSUE TITLE
Can't start deamon

### ISSUE THREAD

**Issue by martysto** [ALQOCRYPTO/ALQO#13]
Trying to start alqod yields:
./alqod: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

System: 4.14.53-1-MANJARO 
installed: boost-libs  1.67.0-4

**Comment by martysto** [comment]
Same on Ubuntu Server
4.15.0-23-generic #25-Ubuntu

**Comment by martysto** [comment]
I suppose you have the same issue.
You wallet is only compatible with older Linux releases ...

error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file

The issue is downgrading the libboost causes a host of issues, making the system unusable.

**Comment by martysto** [comment]
Compiling also fails: 
`configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!`

There is no LibreSSL installed.

**Comment by martysto** [comment]
This is essentially the same issue:
https://github.com/PIVX-Project/PIVX/issues/149

**Comment by KevinCollmer** [comment]
Should be fixed in the new atlas release
