### ISSUE TITLE
Deleted PIVX Developers entries in the License and Copying file.

### ISSUE THREAD

**Issue by Evan-PIVX** [ALQOCRYPTO/ALQO#17]
The requirements under our open-source MIT use license is that any project may clone and reuse our code base provided that they leave " ALL " Copyright notices in place. This includes the COPYING (license) file as well as all the code headers showing that work has been done by the respective developers, as well as upstream copyrights.

**Comment by mathieuarbezhermoso** [comment]
That should be fixed in a few.
