### ISSUE TITLE
installing wallet in ubuntu 17.10

### ISSUE THREAD

**Issue by somhi** [ALQOCRYPTO/ALQO#2]
I'm trying to install ALQO wallet in Ubuntu 17.10 and I had lots of problems.

I've downloaded official wallet from website and lots of dependencies were missing. Tried to solve them but I got stuck at some point.
./alqod: symbol lookup error: ./alqod: undefined symbol: _ZN5boost11this_thread5hiden9sleep_forERK8timespec

Later I tried to download latest source code from Github repositori. After successful ./autogen.sh  I got stuck at ./configure   
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing

Also I want to know when are you going to deliver a light wallet.

Regards,

**Comment by MoNTE48** [comment]
@somhi sudo apt-get install libdb++-dev

**Comment by KevinCollmer** [comment]
#closed as it seems to be fixed
