### ISSUE TITLE
Unable to start MN v3.0.0.1-a3e990b-dirty from wallet 3.0.0.1 or 2.1.0.1

### ISSUE THREAD

**Issue by walkjivefly** [ALQOCRYPTO/ALQO#3]
Since no-one is responding to this problem in Discord....

Recompiled MN daemon from Github latest (commit a3e990b8e10a306d134c2b391c9939936a9a5667) (on Ubuntu 16.04). Stopped the (v2.1.0.1) MN and (re-)started new (v3.0.0.1) version. MN status showed as Hot node, awaiting activation.

Tried to start from remote 2.1.0.1 wallet. Wallet said started but masternode status showed no change. 
Tried to start from remote 3.0.0.1 wallet. Wallet said started but masternode status showed no change.

That was 2 days ago. Still waiting for a wallet which can actually start a 3.0.0.1 MN

**Comment by KevinCollmer** [comment]
We've just released the new QT's for v3.0

https://github.com/ALQOCRYPTO/ALQO/releases
