### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by StarPool** [ALQOCRYPTO/ALQO#4]
OS: Ubuntu 16.04
Source: latest source

execute `alqo-cli gettemplateblock`
show error:
```
error: {"code":-7,"message":"Out of memory"}
```

`alqo-cli getinfo`
```
{
    "version" : 3000001,
    "protocolversion" : 70713,
    "walletversion" : 61000,
    "balance" : 0.40721397,
    "Darksend_balance" : 0.00000000,
    "blocks" : 218496,
    "timeoffset" : 0,
    "connections" : 12,
    "proxy" : "",
    "difficulty" : 421454.39073969,
    "testnet" : false,
    "keypoololdest" : 1512811091,
    "keypoolsize" : 1000,
    "unlocked_until" : 0,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00010000,
    "staking status" : "Staking Not Active",
    "errors" : ""
}
```

**Comment by phm87** [comment]
The same issue "Out of memory" happened on our side with the new version of ALQO code, after commit:
https://github.com/ALQOCRYPTO/ALQO/commit/7cfb326696549e18a9ade4c45af7de6da443e7cf

I don't have more details than @StarPool 

Thank you

**Comment by nasherin0** [comment]
hi,

look like the error occurs here :
https://github.com/ALQOCRYPTO/ALQO/blob/72a6d1620574b8d855670eb6599618bdcd3407c7/src/rpcmining.cpp#L497

https://github.com/ALQOCRYPTO/ALQO/blob/4b91feb86ac651d6b78e0c450fe2f50d1b56feb7/src/miner.cpp#L94

nothing changed in last commits so probably isolated.
my advice is to try pre-compilated cause something went wrong with the compilation probably

**Comment by KevinCollmer** [comment]
fixed in https://github.com/ALQOCRYPTO/ALQO/commit/6823bbf48430e11a42e10be8872d4df2de1e21cd
