### ISSUE TITLE
Solus OS 

### ISSUE THREAD

**Issue by pivxslimjim** [ALQOCRYPTO/ALQO#5]
./alqod: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./alqod)
./alqod: /usr/lib/libssl.so.1.0.0: no version information available (required by ./alqod)
./alqod: symbol lookup error: ./alqod: undefined symbol: _ZN5boost11this_thread5hiden9sleep_forERK8timespec

ALQO 3.2 / Solus 3.999

**Comment by KevinCollmer** [comment]
Please update to the latest version of ALQO and install all dependencies.
