### ISSUE TITLE
Alqod strange issue

### ISSUE THREAD

**Issue by ikabsd** [ALQOCRYPTO/ALQO#6]
error -3: mining was disabled. I see in source code:

Value getblocktemplate(const Array& params, bool fHelp)
{
        throw JSONRPCError(RPC_TYPE_ERROR, "Mining was disabled.");
}

this means we can't mine ?

mining disabled in latest commit? https://github.com/ALQOCRYPTO/ALQO/commit/6f7c48f6776af6b1b1134a2cdad2f9916f1bf468

Thank you

**Comment by pmaccamp** [comment]
running into same issue

**Comment by ikabsd** [comment]
anyone????
