### ISSUE TITLE
no connecgtion to alqo

### ISSUE THREAD

**Issue by dg1kwa** [ALQOCRYPTO/ALQO#8]
Hi,
I down the cliebt V3.2 and start, but no connection to alqo network.

I try with win 10 64bit and Linux.

Internetconnection is ok and i have a offical IPv4/6 address ... debug.log not help really.

What happen?

Regards
 Andreas

**Comment by yannickxyz** [comment]
Using the new alqo-qt v3.5 fixx this issues.
